as yet unclassified
testSlippers

	self assert: 'slippers' equals:   (roulette ball: 0).
	self assert: 'slippers' equals:   (roulette ball: 4).
	self assert: 'slippers' equals:   (roulette ball: 20).
	self assert: 'slippers' equals:   (roulette ball: 30).
	self assert: 'slippers' equals:   (roulette ball: 60).
	self assert: 'slippers' equals:   (roulette ball: 65).
	self assert: 'slippers' equals:   (roulette ball: 69).