as yet unclassified
setUpPuzzle

	mansNationality := QuantumObject possibilities: #(japanese spaniard norwegian english ukrainian).  
	pet := QuantumObject possibilities: #(dog snails).
	smoke := QuantumObject possibilities: #(oldGold  kool  parliaments luckyStrike).
	color := QuantumObject possibilities: #(red green ivory blue yellow).
	drink := QuantumObject possibilities: #(tea coffee milk orangeJuice.).