versions
version127: spec 
	<version: '12.7' imports: #('6.0-baseline') >
	"7 December 2012"
	spec for: #common do: [
		spec blessing: #development.
		spec package: 'Ani' with: 'Ani-hjo.44'.
		spec package: 'AppleScriptProgrammer' with: 'AppleScriptProgrammer-hjo.13'.
		spec package: 'ArtificalMouseClick' with: 'ArtificalMouseClick-HwaJong.2'.
		spec package: 'BinarySearch' with:  'BinarySearch-hjo.8'.
		spec package: 'BlackBoxParser' with: 'BlackBoxParser-hjo.12'.
		spec package: 'BloodType' with:  'BloodType-hjo.2'.
		spec package: 'ChooseOrEnter' with: 'ChooseOrEnter-HwaJong.2'.
		spec package: 'ClassFilter' with: 'ClassFilter-HwaJong.4'.
		spec package: 'CoolEnumerations' with: 'CoolEnumerations-HwaJong.1'.
		spec package: 'CopyHierarchy' with:  'CopyHierarchy-HwaJong.12'.
		spec package: 'Croquis' with: 'Croquis-HwaJong.14'.
		spec package: 'Daliot' with: 'Daliot-HwaJong.132'.
		spec package: 'DaliotsMappers' with: 'DaliotsMappers-hjo.3'.
		spec package: 'DefragFAT' with: 'DefragFAT-hjo.50'.
		spec package: 'DependencySorter' with: 'DependencySorter-hjo.3'.
		spec package: 'DevPacerCommon' with: 'DevPacerCommon-HwaJong.19'.
		spec package: 'DiceRoller' with: 'DiceRoller-hjo.3'.
		spec package: 'DijEvolution' with: 'DijEvolution-HwaJong.27'.
		spec package: 'Distinction' with: 'Distinction-HwaJong.1'.
		spec package: 'DocumentLogic' with: 'DocumentLogic-HwaJong.25'.
		spec package: 'DrillDownMethodSearch' with: 'DrillDownMethodSearch-HwaJong.103'.
		spec package: 'Graph' with:  'Graph-hjo.15'.
		spec package: 'HangmanRescue' with:  'HangmanRescue-hjo.1'.
		spec package: 'HashProof' with: 'HashProof-HwaJong.8'.
		spec package: 'ImageFamilyTree' with: 'ImageFamilyTree-hjo.27'.
		spec package: 'ImageFootprint' with: 'ImageFootprint-hjo.15'.
		spec package: 'InteractiveBisect' with: 'InteractiveBisect-hjo.12'.
		spec package: 'Jihachol' with:  'Jihachol-hjo.34'.
		spec package: 'LazyRabbit' with:  'LazyRabbit-hjo.28'.
		spec package: 'MaxClub' with:  'MaxClub-hjo.8'.
		spec package: 'MorphoPhysics' with:  'MorphoPhysics-hjo.32'.
		spec package: 'MoveClass' with: 'MoveClass-HwaJong.1'.
		spec package: 'MultiDimensionalEnumeration' with:  'MultiDimensionalEnumeration-HwaJong.9'.
		spec package: 'MultiQuoAndRem' with:  'MultiQuoAndRem-hjo.2'.
		spec package: 'NumericalError' with: 'NumericalError-HwaJong.1'.
		spec package: 'ObjectDiff' with: 'ObjectDiff-HwaJong.58'.
		spec package: 'PCube' with:  'PCube-HwaJong.12'.
		spec package: 'PhileasFogg' with:  'PhileasFogg-hjo.36'.
		spec package: 'PocketCube' with:  'PocketCube-HwaJong.175'.
		spec package: 'Prolog' with:  'Prolog-HwaJong.18'.
		spec package: 'QuantumLogic' with: 'QuantumLogic-HwaJong.36'.
		spec package: 'Range' with: 'Range-hjo.7'.
		spec package: 'Roulette' with:  'Roulette-HwaJong.4'.
		spec package: 'Sieve' with: 'Sieve-HwaJong.8'.
		spec package: 'SketchupRuby' with: 'SketchupRuby-hjo.3'.
		spec package: 'SmalltalkQuiz' with: 'SmalltalkQuiz-hjo.9'.
		spec package: 'SortDescriptors' with: 'SortDescriptors-hjo.6'.
		spec package: 'SourceCodeTourGuideCommon' with: 'SourceCodeTourGuideCommon-HwaJong.55'.
		spec package: 'SourceCodeTourGuideOmniBrowser' with: 'SourceCodeTourGuideOmniBrowser-HwaJong.4'.
		spec package: 'StatPseudoCollections' with: 'StatPseudoCollections-hjo.1'.
		spec package: 'StatisticalObjects' with: 'StatisticalObjects-hjo.2'.
		spec package: 'TaxReport' with: 'TaxReport-HwaJong.43'.
		spec package: 'TechnologyTreeOptimizationOfTheCivilizationRevolution' with: 'TechnologyTreeOptimizationOfTheCivilizationRevolution-hjo.1'.
		spec package: 'TestableGraphics' with: 'TestableGraphics-hjo.5'.
		spec package: 'TGListModel' with: 'TGListModel-HwaJong.6'.
		spec package: 'ToolDad' with: 'ToolDad-hjo.4'.
		spec package: 'UndoRedo' with: 'UndoRedo-hjo.1'.
		spec package: 'Unification' with: 'Unification-HwaJong.11'.
		spec package: 'WaffleLayout' with: 'WaffleLayout-hjo.12'.
		spec package: 'WoodCutPictures' with:  'WoodCutPictures-hjo.6'.
		].
	spec for: #'pharo1.4.x' do: [
		spec package: 'DevPacerPharo14' with: 'DevPacerPharo14-hjo.8'.
		spec package: 'SourceCodeTourGuidePharo14' with: 'SourceCodeTourGuidePharo14-hjo.2'.
		].
	spec for: #'pharo2.0.x' do: [
		spec package: 'DevPacerPharo20' with: 'DevPacerPharo20-HwaJong.1'.
		].