initialize-release
initializeBitizens
	"self newBitizenName: '' dreamJobName: '' homeFoorNumber:  food:  service:  recreation:  retail:  creative:  employedAt: ''."
	bitizens :=
	{
		self newBitizenName: 'SHIRLEY BYRD' dreamJobName: 'ART STUDIO' homeFoorNumber: 5 food: 0 service: 3 recreation: 3 retail: 6 creative: 9 employedAt: 'PHOTO STUDIO'.
		self newBitizenName: 'PENNY GARCIA' dreamJobName: 'ROCK CLIMBING' homeFoorNumber: 8 food: 2 service: 4 recreation: 9 retail: 1 creative: 9 employedAt: 'PHOTO STUDIO'.		
		self newBitizenName: 'MAXINE COOPER' dreamJobName: 'SHIP & PRINT' homeFoorNumber: 2 food: 8 service: 9 recreation: 7 retail: 8 creative: 9 employedAt: 'PHOTO STUDIO'.
		self newBitizenName: 'ELAINE BAILEY' dreamJobName: 'HEALTH CLUB' homeFoorNumber: 2 food: 8 service: 9 recreation: 7 retail: 8 creative: 9 employedAt: 'HAT SHOP'.
		self newBitizenName: 'C. BENNETT' dreamJobName: 'GAME STUDIO' homeFoorNumber: 10 food: 2 service: 7 recreation: 5 retail: 0 creative: 8 employedAt: ''.
		self newBitizenName: 'DAWN PEARSON' dreamJobName: 'POTTERY STUDIO' homeFoorNumber: 5 food: 2 service: 4 recreation: 5 retail: 7 creative: 8 employedAt: 'HAT SHOP'.
	}