initialize-release
initializeFloors
	floors :=
	{
		ResidentFloor number: 2.
		CommercialFloor number: 3 job: (Job greenJobName: 'SUB SHOP').
		CommercialFloor number: 4 job: (Job purpleJobName: 'HAT SHOP').
		ResidentFloor number: 5.
		CommercialFloor number: 6 job: (Job ivoryJobName: 'VIDEO RENTAL').
		CommercialFloor number: 7 job: (Job crimsonJobName: 'PHOTO STUDIO').
		ResidentFloor number: 8.
		CommercialFloor number: 9 job: (Job ivoryJobName: 'PLANETARIUM').
		ResidentFloor number: 10.
	}.