instance creation
bitName: aByteString dreamJobName: aByteString2 food: aSmallInteger service: aSmallInteger4 recreation: aSmallInteger5 retail: aSmallInteger6 creative: aSmallInteger7 
	^self new
		bitName: aByteString;
		foodAbility: aSmallInteger;
		serviceAbility: aSmallInteger4;
		recreationAbility: aSmallInteger5;
		retailAbility: aSmallInteger6;
		creativeAbility: aSmallInteger7;
		dreamJobName: aByteString2