as yet unclassified
setUpTechRequirements

	self setUpRequirementTechsOfTechNamed: 'Ceremonial Burial' withTechNames: {'Pottery'}.
	self setUpRequirementTechsOfTechNamed: 'Iron Working' withTechNames: {'Bronze Working'}.
	self setUpRequirementTechsOfTechNamed: 'Masonry' withTechNames: {'Pottery'}.
	self setUpRequirementTechsOfTechNamed: 'Writing' withTechNames:  {'Alphabet'}.
	self setUpRequirementTechsOfTechNamed: 'Code of Laws' withTechNames:  {'Alphabet'. 'Writing'}.
	self setUpRequirementTechsOfTechNamed: 'Construction' withTechNames:  {'Iron Working'. 'Masonry'}.
	self setUpRequirementTechsOfTechNamed: 'Irrigation' withTechNames:  {'Pottery'. 'Masonry'}.
	self setUpRequirementTechsOfTechNamed: 'Literacy' withTechNames:  {'Alphabet'. 'Writing'}.
	self setUpRequirementTechsOfTechNamed: 'Mathematics' withTechNames:  {'Masonry'. 'Writing'}.
	self setUpRequirementTechsOfTechNamed: 'Currency' withTechNames:  {'Bronze Working'. 'Code of Laws'}.
	self setUpRequirementTechsOfTechNamed: 'Democracy' withTechNames:  {'Code of Laws'. 'Literacy'}.
	self setUpRequirementTechsOfTechNamed: 'Engineering' withTechNames:  {'Construction'. 'Mathematics'}.
	self setUpRequirementTechsOfTechNamed: 'Monarchy' withTechNames:  {'Code of Laws'. 'Ceremonial Burial'. 'Writing'}.
	self setUpRequirementTechsOfTechNamed: 'Navigation' withTechNames:  {'Writing'. 'Mathematics'}.
	self setUpRequirementTechsOfTechNamed: 'Feudalism' withTechNames:  {'Monarchy'. 'Horseback Riding'}.
	self setUpRequirementTechsOfTechNamed: 'Religion' withTechNames:  {'Monarchy'. 'Ceremonial Burial'}.
	self setUpRequirementTechsOfTechNamed: 'Banking' withTechNames:  {'Currency'. 'Code of Laws'. 'Literacy'}.
	self setUpRequirementTechsOfTechNamed: 'University' withTechNames:  {'Democracy'. 'Mathematics'. 'Literacy'}.
	self setUpRequirementTechsOfTechNamed: 'Invention' withTechNames:  {'Engineering'. 'Literacy'}.
	self setUpRequirementTechsOfTechNamed: 'Gunpowder' withTechNames:  {'Feudalism'. 'Invention'}.
	self setUpRequirementTechsOfTechNamed: 'Metallurgy' withTechNames:  {'University'. 'Engineering'. 'Iron Working'}.
	self setUpRequirementTechsOfTechNamed: 'Printing Press' withTechNames:  {'Religion'. 'University'}.
	self setUpRequirementTechsOfTechNamed: 'Steam Power' withTechNames:  {'Invention'. 'Engineering'. 'Iron Working'}.
	self setUpRequirementTechsOfTechNamed: 'Combustion' withTechNames:  {'Gunpowder'. 'Metallurgy'. 'Steam Power'}.
	self setUpRequirementTechsOfTechNamed: 'Electricity' withTechNames:  {'Metallurgy'. 'Engineering'. 'Steam Power'}.
	self setUpRequirementTechsOfTechNamed: 'Industrialization' withTechNames:  {'Banking'. 'Steam Power'}.
	self setUpRequirementTechsOfTechNamed: 'Railroad' withTechNames:  {'Steam Power'}.
	self setUpRequirementTechsOfTechNamed: 'Steel' withTechNames:  {'Metallurgy'. 'Steam Power'}.
	self setUpRequirementTechsOfTechNamed: 'Communism' withTechNames:  {'Industrialization'. 'University'}.
	self setUpRequirementTechsOfTechNamed: 'Flight' withTechNames:  {'Combustion'. 'Metallurgy'. 'Invention'}.
	self setUpRequirementTechsOfTechNamed: 'Mass Production' withTechNames:  {'Industrialization'. 'Railroad'}.
	self setUpRequirementTechsOfTechNamed: 'The Corporation' withTechNames:  {'Industrialization'. 'Banking'}.
	self setUpRequirementTechsOfTechNamed: 'Atomic Theory' withTechNames:  {'University'. 'Invention'. 'Electricity'}.
	self setUpRequirementTechsOfTechNamed: 'The Automobile' withTechNames:  {'Combustion'. 'Steel'}.
	self setUpRequirementTechsOfTechNamed: 'Electronics' withTechNames:  {'The Corporation'. 'Electricity'}.
	self setUpRequirementTechsOfTechNamed: 'Mass Media' withTechNames:  {'The Corporation'. 'Printing Press'}.
	self setUpRequirementTechsOfTechNamed: 'Advanced Flight' withTechNames:  {'Industrialization'. 'Flight'}.
	self setUpRequirementTechsOfTechNamed: 'Nuclear Power' withTechNames:  {'Mass Production'. 'Atomic Theory'}.
	self setUpRequirementTechsOfTechNamed: 'Networking' withTechNames:  {'Electronics'. 'The Corporation'}.
	self setUpRequirementTechsOfTechNamed: 'Space Flight' withTechNames:  {'Electronics'. 'Advanced Flight'. 'Nuclear Power'}.
	self setUpRequirementTechsOfTechNamed: 'Globalization' withTechNames:  {'Networking'. 'Mass Media'}.
	self setUpRequirementTechsOfTechNamed: 'Superconductor' withTechNames:  {'Space Flight'. 'Mass Production'}.
	self setUpRequirementTechsOfTechNamed: 'Future Technology' withTechNames:  {'Globalization'. 'Superconductor'. 'Advanced Flight'}.