SystemOrganization addCategory: #PocketCube!
SystemOrganization addCategory: 'PocketCube-DijEvolution'!
SystemOrganization addCategory: 'PocketCube-Morph'!
SystemOrganization addCategory: 'PocketCube-Recognizer'!
SystemOrganization addCategory: 'PocketCube-Scramble'!
SystemOrganization addCategory: 'PocketCube-SidePatterns'!
SystemOrganization addCategory: 'PocketCube-Tests'!
SystemOrganization addCategory: 'PocketCube-Waffle'!
