as yet unclassified
testSlippers

	self assert: 'slippers' equals:   (roulette ball: 0).
	self assert: 'slippers' equals:   (roulette ball: 0.3).
	self assert: 'slippers' equals:   (roulette ball: 1).
	self assert: 'slippers' equals:   (roulette ball: 2).
	self assert: 'slippers' equals:   (roulette ball: 3).
	self assert: 'slippers' equals:   (roulette ball: 4).
	self assert: 'slippers' equals:   (roulette ball: 5.11).