on image testing
oneSubclassSubjectPackageChunk
	"get it from following line:

	CAUTION: get rid of methods added by Trait. FileOut does not check if method is from trait or not.
	
		Clipboard clipboardText asString"
^ 'Object subclass: #Wooluspos2
	instanceVariableNames: ''''
	classVariableNames: ''''
	poolDictionaries: ''''
	category: ''WhoolaWhoolaWooWoo-oneSubclass''!


Wooluspos2 subclass: #WoolOnlyOneSubclass
	instanceVariableNames: ''var1''
	classVariableNames: ''''
	poolDictionaries: ''''
	category: ''WhoolaWhoolaWooWoo-oneSubclass''!

!WoolOnlyOneSubclass methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/5/2013 16:33''!
method1
	^self! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

WoolOnlyOneSubclass class
	instanceVariableNames: ''''!

!WoolOnlyOneSubclass class methodsFor: ''as yet unclassified'' stamp: ''HwaJong 12/2/2013 10:54''!
classMethod1
	^1! !
'