on image testing
threeSubclassSubjectPackageChunk
	"get it from following line:

	CAUTION: get rid of methods added by Trait. FileOut does not check if method is from trait or not.
	
		Clipboard clipboardText asString"
^ 'Object subclass: #Wooluspos
	instanceVariableNames: ''c''
	classVariableNames: ''''
	poolDictionaries: ''''
	category: ''WhoolaWhoolaWooWoo-threeSubclass''!

!Wooluspos methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/5/2013 10:16''!
superClassDefinesThisDifferently
	^''superclass is super''! !


!Wooluspos methodsFor: ''category1'' stamp: ''HwaJong 8/3/2013 12:16''!
iShouldBeCategorizedTo1
	^self! !


!Wooluspos methodsFor: ''category2'' stamp: ''HwaJong 8/3/2013 12:16''!
iShouldBeCategorizedTo2
	^self! !


!Wooluspos methodsFor: ''accessing'' stamp: ''HwaJong 8/3/2013 12:16''!
c
	^ c! !

!Wooluspos methodsFor: ''accessing'' stamp: ''HwaJong 8/3/2013 12:16''!
c: anObject
	c := anObject! !


Wooluspos subclass: #WoolClass2
	instanceVariableNames: ''b d''
	classVariableNames: ''Keke''
	poolDictionaries: ''''
	category: ''WhoolaWhoolaWooWoo-threeSubclass''!

!WoolClass2 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
b
	^ b! !

!WoolClass2 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
b: anObject
	b := anObject! !

!WoolClass2 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
d
	^ d! !

!WoolClass2 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
d: anObject
	d := anObject! !


!WoolClass2 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 12/2/2013 16:24''!
havingPragma
	<justADummpyPragma>! !

!WoolClass2 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/4/2013 23:28''!
referingToClassVarKeke

	Keke := 1004.! !

!WoolClass2 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/3/2013 22:24''!
sourceCodeIsNotExactlySame
	^''bye''! !

!WoolClass2 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/5/2013 10:16''!
superClassDefinesThisDifferently
	^''i am cool''! !

!WoolClass2 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/4/2013 00:39''!
superSends
	^super yourself! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

WoolClass2 class
	instanceVariableNames: ''''!

!WoolClass2 class methodsFor: ''as yet unclassified'' stamp: ''HwaJong 12/2/2013 10:54''!
classMethod3
	^3! !


Wooluspos subclass: #WoolClass3
	instanceVariableNames: ''a d''
	classVariableNames: ''Keke''
	poolDictionaries: ''''
	category: ''WhoolaWhoolaWooWoo-threeSubclass''!

!WoolClass3 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
a
	^ a! !

!WoolClass3 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
a: anObject
	a := anObject! !

!WoolClass3 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
d
	^ d! !

!WoolClass3 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:22''!
d: anObject
	d := anObject! !


!WoolClass3 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 12/2/2013 16:24''!
havingPragma
	<justADummpyPragma>! !

!WoolClass3 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/4/2013 23:29''!
referingToClassVarKeke

	Keke := 1004.! !

!WoolClass3 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/3/2013 22:24''!
sourceCodeIsNotExactlySame
	^''hello''! !

!WoolClass3 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/5/2013 10:16''!
superClassDefinesThisDifferently
	^''i am cool''! !

!WoolClass3 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/4/2013 00:39''!
superSends
	^super yourself! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

WoolClass3 class
	instanceVariableNames: ''''!

!WoolClass3 class methodsFor: ''as yet unclassified'' stamp: ''HwaJong 12/2/2013 10:54''!
classMethod3
	^3! !


Wooluspos subclass: #WoolClass1
	instanceVariableNames: ''a b''
	classVariableNames: ''Keke''
	poolDictionaries: ''''
	category: ''WhoolaWhoolaWooWoo-threeSubclass''!

!WoolClass1 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:21''!
a
	^ a! !

!WoolClass1 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:21''!
a: anObject
	a := anObject! !

!WoolClass1 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:21''!
b
	^ b! !

!WoolClass1 methodsFor: ''accessing'' stamp: ''HwaJong 5/3/2013 20:21''!
b: anObject
	b := anObject! !


!WoolClass1 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 12/2/2013 16:24''!
havingPragma
	<justADummpyPragma>! !

!WoolClass1 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/4/2013 23:30''!
referingToClassVarKeke

	Keke := 1004.! !

!WoolClass1 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/3/2013 22:24''!
sourceCodeIsNotExactlySame
	^''hello''! !

!WoolClass1 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/5/2013 10:16''!
superClassDefinesThisDifferently
	^''i am cool''! !

!WoolClass1 methodsFor: ''as yet unclassified'' stamp: ''HwaJong 5/4/2013 00:39''!
superSends
	^super yourself! !

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

WoolClass1 class
	instanceVariableNames: ''''!

!WoolClass1 class methodsFor: ''as yet unclassified'' stamp: ''HwaJong 12/2/2013 10:54''!
classMethod3
	^3! !
'