initializing
initializeSidesWithColors

	self topSide: (PocketCubeSide ofAllSamePieces: Color red).
	self leftSide: (PocketCubeSide ofAllSamePieces: Color white).
	self bottomSide: (PocketCubeSide ofAllSamePieces: Color orange).
	self rightSide: (PocketCubeSide ofAllSamePieces: Color yellow).
	self frontSide: (PocketCubeSide ofAllSamePieces: Color green).
	self backSide: (PocketCubeSide ofAllSamePieces: Color blue).